/* Generated By:JavaCC: Do not edit this line. OSQLConstants.java */
package whu.oddb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK = 1;
  /** RegularExpression Id. */
  int LP = 2;
  /** RegularExpression Id. */
  int RP = 3;
  /** RegularExpression Id. */
  int SEMI = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int ARROW = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int COMPARE_OP = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int CREATE = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int SELECTDEPUTY = 16;
  /** RegularExpression Id. */
  int AS = 17;
  /** RegularExpression Id. */
  int FROM = 18;
  /** RegularExpression Id. */
  int WHERE = 19;
  /** RegularExpression Id. */
  int DROP = 20;
  /** RegularExpression Id. */
  int INSERT = 21;
  /** RegularExpression Id. */
  int INTO = 22;
  /** RegularExpression Id. */
  int DELETE = 23;
  /** RegularExpression Id. */
  int UPDATE = 24;
  /** RegularExpression Id. */
  int VALUES = 25;
  /** RegularExpression Id. */
  int SET = 26;
  /** RegularExpression Id. */
  int TYPE = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int INT_VALUE = 29;
  /** RegularExpression Id. */
  int FLOAT_VALUE = 30;
  /** RegularExpression Id. */
  int STRING_VALUE = 35;
  /** RegularExpression Id. */
  int CHAR_VALUE = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;
  /** Lexical state. */
  int IN_CHARACTER = 2;
  /** Lexical state. */
  int CHARACTER_TERM = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<BLANK>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"->\"",
    "\".\"",
    "\"=\"",
    "<COMPARE_OP>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<CREATE>",
    "<SELECT>",
    "<CLASS>",
    "<SELECTDEPUTY>",
    "<AS>",
    "<FROM>",
    "<WHERE>",
    "<DROP>",
    "<INSERT>",
    "<INTO>",
    "<DELETE>",
    "<UPDATE>",
    "<VALUES>",
    "<SET>",
    "<TYPE>",
    "<ID>",
    "<INT_VALUE>",
    "<FLOAT_VALUE>",
    "\"\\\"\"",
    "<token of kind 32>",
    "<token of kind 33>",
    "<token of kind 34>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<token of kind 37>",
    "<token of kind 38>",
    "<token of kind 39>",
    "\"\\\'\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
